//This is entry point of the kotlin.
fun main() {
    //this the body of the function...
    //Code in the body gets executed...
    print("Hello World!!!")
    //This prints Hello World to the terminal...
    //Do the same code using println and observe the difference...
}